
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["TrainingEvents.Web.Api/TrainingEvents.Web.Api.csproj", "./TrainingEvents.Web.Api/"]
RUN dotnet restore "./TrainingEvents.Web.Api/TrainingEvents.Web.Api.csproj"
COPY . ./
RUN dotnet build "./TrainingEvents.Web.Api/TrainingEvents.Web.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./TrainingEvents.Web.Api/TrainingEvents.Web.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TrainingEvents.Web.Api.dll"]
