FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["TE.Server.Events/TE.Server.Events.csproj", "./TE.Server.Events/"]
RUN dotnet restore "TE.Server.Events/TE.Server.Events.csproj"
COPY . ./
RUN dotnet build "./TE.Server.Events/TE.Server.Events.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./TE.Server.Events/TE.Server.Events.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TE.Server.Events.dll"]
