version: '3.7'

services:

  client.ui:
    stdin_open: true
    container_name: client-ui
    build:
      context: .
      dockerfile: Dockerfile_Client
    ports:
      - 3000:3000
    environment:
    #Apparently React Uses Polling to Watch for Changes to File in Dev Servers
      - CHOKIDAR_USEPOLLING=true

  web.api:
    container_name: web-api
    build:
      context: .
      dockerfile: Dockerfile_WebApi
    ports:
      - 3007:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  event.microservice.api:
    container_name: event-microservice-api
    build:
      context: .
      dockerfile: Dockerfile_Microservice
    ports:
      - 3006:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
