version: '3.7'

services:

  client.ui:
    container_name: client-ui
    build:
      context: .
      dockerfile: Client/training-events-web-ui/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:80
    environment:
    #Apparently React Uses Polling to Watch for Changes to File in Dev Servers
      - CHOKIDAR_USEPOLLING=true

  web.api:
    container_name: web-api
    build:
      context: .
      dockerfile: TrainingEvents.Web.Api/Dockerfile
    ports:
      - 3007:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  event.microservice.api:
    container_name: event-microservice-api
    build:
      context: .
      dockerfile: TE.Server.Events/Dockerfile
    ports:
      - 3006:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
